### ISSUE TITLE
XSDL portrait mode + mouse emulation(large,tablets) not working correctly

### ISSUE THREAD

**Issue by edgar444** [pelya/commandergenius#32] opened 2014-09-28 12:40 UTC
When moving finger from left-to-right & top-to-bottom WM mouse cursor is incrementally going further away from the finger to the left & bottom.

This happens only in portrait mode. In landscape the problem does not exsist.

How to reproduce:
Settings :
"Video settings" > "Portrait/vertical.screen orientation"
"Mouse emulation" > "Mouse emulation mode" > "Large (tablets)"  or "Small, magnifying glass"

**Comment by mpcjanssen** [comment] 2014-10-16 10:43
Did you disable the gyroscopic sensor movement?

**Comment by pelya** [comment] 2014-10-16 11:21
No, but I'm planning to do this, because it's not very useful.
You can enable or disable it using SDL start-up config dialog.

**Comment by mpcjanssen** [comment] 2014-10-16 13:47
In was asking the issue logger because this looks like an issue with the phone/tablet not being level.

**Comment by pelya** [comment] 2014-10-16 13:59
Gyroscope only detects movement, it does not matter if the phone is
horizontal or not. When you move mouse cursor without moving the tablet,
the gyroscope offset is slowly decreases to zero.

**Comment by mpcjanssen** [comment] 2014-10-16 15:04
I wasn't aware of that. Good to know.

**Comment by edgar444** [comment] 2014-10-19 11:11
No, i have gyroscope disabled.

**Comment by pelya** [comment] 2015-01-01 23:13
Cannot reproduce, closing this bug.

**Closed as completed by pelya** 2015-01-01 23:13 UTC
